### ISSUE TITLE
Message is too long

### ISSUE THREAD

**Issue by moxxiq** [Na3aga/gmbot#17]
Received those logs
```
2020-10-05T21:53:08.191142+00:00 app[web.1]: error_handler.py [LINE:48] #ERROR    [2020-10-05 21:53:08,186]  TelegramAPIError: Message is too long
2020-10-05T21:53:08.191154+00:00 app[web.1]: Update: {"update_id": 352411293, "message": {"message_id": 950, "from": {"id": 255808540, "is_bot": false, "first_name": "Dmytro", "last_name": "Bubela", "username": "moxxiq", "language_code": "en"}, "chat": {"id": 255808540, "first_name": "Dmytro", "last_name": "Bubela", "username": "moxxiq", "type": "private"}, "date": 1601934787, "text": "/last dimanavsisto@gmail.com", "entities": [{"offset": 0, "length": 5, "type": "bot_command"}, {"offset": 6, "length": 22, "type": "email"}]}}
2020-10-05T21:53:08.191156+00:00 app[web.1]: Traceback (most recent call last):
2020-10-05T21:53:08.191157+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
2020-10-05T21:53:08.191158+00:00 app[web.1]: return await self.message_handlers.notify(update.message)
2020-10-05T21:53:08.191158+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
2020-10-05T21:53:08.191159+00:00 app[web.1]: response = await handler_obj.handler(*args, **partial_data)
2020-10-05T21:53:08.191160+00:00 app[web.1]: File "/app/TgBot/handlers/users/last.py", line 29, in last_email
2020-10-05T21:53:08.191160+00:00 app[web.1]: await message.answer(msg['text'])
2020-10-05T21:53:08.191160+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/types/message.py", line 316, in answer
2020-10-05T21:53:08.191161+00:00 app[web.1]: return await self.bot.send_message(
2020-10-05T21:53:08.191161+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/bot.py", line 219, in send_message
2020-10-05T21:53:08.191162+00:00 app[web.1]: result = await self.request(api.Methods.SEND_MESSAGE, payload)
2020-10-05T21:53:08.191162+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/base.py", line 200, in request
2020-10-05T21:53:08.191163+00:00 app[web.1]: return await api.make_request(self.session, self.__token, method, data, files,
2020-10-05T21:53:08.191164+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/api.py", line 104, in make_request
2020-10-05T21:53:08.191164+00:00 app[web.1]: return check_result(method, response.content_type, response.status, await response.text())
2020-10-05T21:53:08.191165+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/api.py", line 78, in check_result
2020-10-05T21:53:08.191165+00:00 app[web.1]: exceptions.BadRequest.detect(description)
2020-10-05T21:53:08.191165+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 137, in detect
2020-10-05T21:53:08.191166+00:00 app[web.1]: raise err(cls.text or description)
2020-10-05T21:53:08.191166+00:00 app[web.1]: aiogram.utils.exceptions.MessageIsTooLong: Message is too long
2020-10-05T21:53:08.191698+00:00 app[web.1]: web_log.py [LINE:233] #INFO     [2020-10-05 21:53:08,191]  10.14.25.48 [05/Oct/2020:21:53:07 +0000] "POST /webhook/lewis/ HTTP/1.1" 200 171 "-" "-"
2020-10-05T21:53:08.192792+00:00 heroku[router]: at=info method=POST path="/webhook/lewis/" host=lewis-bots.herokuapp.com request_id=bc77a3e0-b9be-40de-8e04-5c44179789fd fwd="91.108.6.108" dyno=web.1 connect=0ms service=1049ms status=200 bytes=171 protocol=https
```

to file https://drive.google.com/file/d/1-M_7E8fqxuZ4cItLshf1eerPIqAAZiKR/view?usp=sharing

**Comment by moxxiq** [comment]
The simple solution just to split text and send all parts separately https://github.com/Na3aga/gmbot/blob/3e673b431837e67679a2c50082ec1558ad339691/TgBot/handlers/users/last.py#L29
